// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace RiverBooks.Books.Data.Migrations
{
    [DbContext(typeof(BookDbContext))]
    [Migration("20250502070754_Second")]
    partial class Second
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Books")
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RiverBooks.Books.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Books", "Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6d15efde-a7e0-4a51-a942-c7b431a390d1"),
                            Author = "J.R.R. Tolkien",
                            Price = 10.99m,
                            Title = "The Hobbit"
                        },
                        new
                        {
                            Id = new Guid("d736edba-562d-4857-8215-a5db699a0180"),
                            Author = "J.R.R. Tolkien",
                            Price = 29.99m,
                            Title = "The Lord of the Rings"
                        },
                        new
                        {
                            Id = new Guid("666c8c03-7891-43e4-8da7-d803569e7aba"),
                            Author = "J.R.R. Tolkien",
                            Price = 19.99m,
                            Title = "The Silmarillion"
                        },
                        new
                        {
                            Id = new Guid("137cea4e-334c-4841-9a5c-776487084423"),
                            Author = "J.R.R. Tolkien",
                            Price = 14.99m,
                            Title = "The Children of Húrin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
