// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace RiverBooks.Books.Data.Migrations
{
    [DbContext(typeof(BookDbContext))]
    [Migration("20250420192621_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Books")
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RiverBooks.Books.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Books", "Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("303d9a8a-f308-4359-ab05-df603b1b3b09"),
                            Author = "J.R.R. Tolkien",
                            Price = 10.99m,
                            Title = "The Hobbit"
                        },
                        new
                        {
                            Id = new Guid("cc3b29e8-3e6a-42ee-9bd3-e5fdaf54a0f8"),
                            Author = "J.R.R. Tolkien",
                            Price = 29.99m,
                            Title = "The Lord of the Rings"
                        },
                        new
                        {
                            Id = new Guid("0d35d8b6-3958-49e5-a9cb-7ce868303e84"),
                            Author = "J.R.R. Tolkien",
                            Price = 19.99m,
                            Title = "The Silmarillion"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
