// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RiverBooks.Books.Data;

#nullable disable

namespace RiverBooks.Books.Data.Migrations
{
    [DbContext(typeof(BookDbContext))]
    [Migration("20250502112956_Thirtd")]
    partial class Thirtd
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Books")
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RiverBooks.Books.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Books", "Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ac76deab-e2c4-4726-a244-3288ae9f4244"),
                            Author = "J.R.R. Tolkien",
                            Price = 10.99m,
                            Title = "The Hobbit"
                        },
                        new
                        {
                            Id = new Guid("ddbde630-efcc-4a88-a9a1-6000355c13bc"),
                            Author = "J.R.R. Tolkien",
                            Price = 29.99m,
                            Title = "The Lord of the Rings"
                        },
                        new
                        {
                            Id = new Guid("5f7827d3-ddb9-42fe-9670-42c971f49a37"),
                            Author = "J.R.R. Tolkien",
                            Price = 19.99m,
                            Title = "The Silmarillion"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
